# Generated by Django 4.0.3 on 2022-08-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rencai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiyeusername', models.CharField(blank=True, max_length=200, null=True)),
                ('yonghuusername', models.CharField(blank=True, max_length=200, null=True)),
                ('zhiwei', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, default='0', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('identity', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('advantage', models.CharField(blank=True, max_length=200, null=True)),
                ('work', models.CharField(blank=True, max_length=200, null=True)),
                ('qwyx', models.CharField(blank=True, max_length=200, null=True)),
                ('gsmc', models.CharField(blank=True, max_length=200, null=True)),
                ('timeq', models.CharField(blank=True, max_length=200, null=True)),
                ('timez', models.CharField(blank=True, max_length=200, null=True)),
                ('job', models.CharField(blank=True, max_length=200, null=True)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
                ('etimeq', models.CharField(blank=True, max_length=200, null=True)),
                ('etimez', models.CharField(blank=True, max_length=200, null=True)),
                ('success', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
