# Generated by Django 3.2 on 2022-07-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_auto_20220730_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo1',
            name='success',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
