# Generated by Django 4.0.3 on 2022-08-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
