# Generated by Django 4.0.3 on 2022-08-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0003_disc_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disc',
            name='op0',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op1',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op10',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op11',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op12',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op13',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op14',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op15',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op16',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op17',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op18',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op19',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op2',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op20',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op21',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op22',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op23',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op24',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op25',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op26',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op27',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op28',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op29',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op3',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op30',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op31',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op32',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op33',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op34',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op35',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op36',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op37',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op38',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op39',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op4',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op5',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op6',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op7',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op8',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='op9',
            field=models.SmallIntegerField(blank=True, max_length=200, null=True),
        ),
    ]
