# Generated by Django 3.2 on 2022-08-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0003_userinfo1_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rencai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiyeusername', models.CharField(blank=True, max_length=200, null=True)),
                ('yonghuusername', models.CharField(blank=True, max_length=200, null=True)),
                ('zhiwei', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, default='0', max_length=200, null=True)),
            ],
        ),
    ]
