# Generated by Django 3.2 on 2022-08-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0004_rencai'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rencai',
        ),
        migrations.AddField(
            model_name='userinfo1',
            name='qiyeusername',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userinfo1',
            name='status',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userinfo1',
            name='yonghuusername',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userinfo1',
            name='zhiwei',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
