# Generated by Django 3.2 on 2022-08-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0006_remove_userinfo1_qiyeusername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo1',
            old_name='yonghuusername',
            new_name='qiyeusername',
        ),
    ]
