# Generated by Django 3.2 on 2022-08-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0007_rename_yonghuusername_userinfo1_qiyeusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rencai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiyeusername', models.CharField(blank=True, max_length=200, null=True)),
                ('yonghuusername', models.CharField(blank=True, max_length=200, null=True)),
                ('zhiwei', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, default='0', max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo1',
            name='qiyeusername',
        ),
        migrations.RemoveField(
            model_name='userinfo1',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userinfo1',
            name='zhiwei',
        ),
    ]
