# Generated by Django 3.2 on 2022-08-17 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0009_auto_20220810_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='tiaojian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('congye', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='zhiye',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zhiyename', models.CharField(blank=True, max_length=200, null=True)),
                ('zhiyejianjie', models.CharField(blank=True, max_length=200, null=True)),
                ('renwu', models.CharField(blank=True, max_length=200, null=True)),
                ('zige', models.CharField(blank=True, max_length=200, null=True)),
                ('gongju', models.CharField(blank=True, max_length=200, null=True)),
                ('tiaojian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.tiaojian')),
            ],
        ),
    ]
