# Generated by Django 3.2 on 2022-08-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0010_tiaojian_zhiye'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('op0', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op1', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op2', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op3', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op4', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op5', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op6', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op7', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op8', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op9', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op10', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op11', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op12', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op13', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op14', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op15', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op16', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op17', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op18', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op19', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op20', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op21', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op22', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op23', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op24', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op25', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op26', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op27', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op28', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op29', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op30', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op31', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op32', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op33', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op34', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op35', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op36', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op37', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op38', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('op39', models.SmallIntegerField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='zhiye',
            old_name='gongju',
            new_name='cygj',
        ),
        migrations.RenameField(
            model_name='zhiye',
            old_name='renwu',
            new_name='jieshao',
        ),
        migrations.RenameField(
            model_name='zhiye',
            old_name='zhiyejianjie',
            new_name='zhize',
        ),
        migrations.AlterField(
            model_name='zhiye',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='zhiye',
            name='tiaojian',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='tiaojian',
        ),
    ]
