# Generated by Django 3.2 on 2022-08-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0011_auto_20220821_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
