# Generated by Django 4.0.3 on 2022-08-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0013_zhiye_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='ans',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
