# Generated by Django 4.0.3 on 2022-08-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qiyeuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('headimg', models.ImageField(blank=True, null=True, upload_to='')),
                ('zhiwu', models.CharField(blank=True, max_length=200, null=True)),
                ('shengfenzh', models.CharField(blank=True, max_length=200, null=True)),
                ('qiyename', models.CharField(blank=True, max_length=200, null=True)),
                ('qiyefaren', models.CharField(blank=True, max_length=200, null=True)),
                ('qiyearea', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
                ('qiyetupian', models.ImageField(blank=True, null=True, upload_to='')),
                ('WKHR', models.CharField(blank=True, max_length=200, null=True)),
                ('ATO', models.CharField(blank=True, max_length=200, null=True)),
                ('overtime', models.CharField(blank=True, max_length=200, null=True)),
                ('fldy', models.CharField(blank=True, max_length=200, null=True)),
                ('mt', models.CharField(blank=True, max_length=200, null=True)),
                ('video', models.CharField(blank=True, max_length=200, null=True)),
                ('jbjs', models.CharField(blank=True, max_length=200, null=True)),
                ('cltime', models.CharField(blank=True, max_length=200, null=True)),
                ('http', models.CharField(blank=True, max_length=200, null=True)),
                ('zjob', models.CharField(blank=True, max_length=200, null=True)),
                ('fjob', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('qygm', models.CharField(blank=True, max_length=200, null=True)),
                ('rzzt', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('real_name', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('job', models.CharField(blank=True, max_length=200, null=True)),
                ('grjj', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('panduan', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='zhaopin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gangwei', models.CharField(blank=True, max_length=200, null=True)),
                ('area', models.CharField(blank=True, max_length=200, null=True)),
                ('renshu', models.CharField(blank=True, max_length=200, null=True)),
                ('xingzhi', models.CharField(blank=True, max_length=200, null=True)),
                ('xinzi', models.CharField(blank=True, max_length=200, null=True)),
                ('xueli', models.CharField(blank=True, max_length=200, null=True)),
                ('describe', models.CharField(blank=True, max_length=200, null=True)),
                ('call', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zhiwei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('xingzhi', models.CharField(blank=True, max_length=200, null=True)),
                ('describe', models.CharField(blank=True, max_length=200, null=True)),
                ('leibie', models.CharField(blank=True, max_length=200, null=True)),
                ('yaoqiu', models.CharField(blank=True, max_length=200, null=True)),
                ('xueli', models.CharField(blank=True, max_length=200, null=True)),
                ('key', models.CharField(blank=True, max_length=200, null=True)),
                ('fuli', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('xinzi', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
