# Generated by Django 3.2 on 2022-07-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_zhiwei'),
    ]

    operations = [
        migrations.AddField(
            model_name='qiyeuser',
            name='addwork',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qiyeuser',
            name='rest',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qiyeuser',
            name='worktime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qiyeuser',
            name='xldy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
