# Generated by Django 3.2 on 2022-07-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20220722_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qiyeuser',
            old_name='addwork',
            new_name='ATO',
        ),
        migrations.RenameField(
            model_name='qiyeuser',
            old_name='rest',
            new_name='WKHR',
        ),
        migrations.RenameField(
            model_name='qiyeuser',
            old_name='worktime',
            new_name='fldy',
        ),
        migrations.RenameField(
            model_name='qiyeuser',
            old_name='xldy',
            new_name='overtime',
        ),
    ]
