# Generated by Django 3.2 on 2022-07-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20220722_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='qiyeuser',
            name='mt',
            field=models.ImageField(blank=True, null=True, upload_to='qy_mt/'),
        ),
        migrations.AddField(
            model_name='qiyeuser',
            name='video',
            field=models.ImageField(blank=True, null=True, upload_to='qy_video/'),
        ),
    ]
