# Generated by Django 3.2 on 2022-07-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20220724_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qiyeuser',
            name='logo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qiyeuser',
            name='mt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qiyeuser',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
